[project]
name = "era-forward-financial-manager"
authors = ["Era Forward Team"]
description = "A decentralized platform for managing shared financial commitments"
telemetry = false
requirements = []
[contracts.era-forward-manager]
path = "contracts/era-forward-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
